// here, app/auth/Provider = wrapper VS app/api/auth/[...nextauth]/NExtAuth object {Google provider}
import NextAuth from 'next-auth/next'
import { authOptions } from '../authOptions'

// providers: [] = Authentication options provided to the user
const handler = NextAuth(authOptions)

export { handler as GET, handler as POST }
// the same handler fn. is being exported as 2 different names: GET and POST

/*
Pages: See NextAuth -> Pages
We can replace the autogenerated login and logout pages with our custom ones. Dive into the guide below to learn how.

NextAuth.js automatically creates simple, unbranded authentication pages for handling Sign in, Sign out, Email Verification and displaying error messages.

The options displayed on the sign-up page are automatically generated based on the providers specified in the options passed to NextAuth.js.

To add a custom login page, you can use the pages option:
*/
